package be.lymaes.race.ability;

public enum AbilityKey {

    ONI_EXP,
    ONI_ABSORPTION,
    HYDROPHOBIA,
    MEAT_EATER,
    SILENT_ENTITY,
    FIREBALL,
    CRAFT_PRIMORDIAL_ONI_BLOOD,

    TAMASHI_EXP,
    TAMASHI_EARTH_ABSORPTION,
    FLY_CHARGE,
    FIRE_ASPECT,
    AQUATIC_STRENGTH,
    FEATHER_FALL,
    MONOPHOBIA,
    DIRT_EATER,

    KITSUNE_RAID_EXP,
    KITSUNE_ZONE_EXP,
    FOX_DISGUISE,
    INVISIBILITY,
    PERM_ALLOW_FLY,

    KARYU_MERCHANT_EXP,
    KARYU_ADORER_EXP,
    KARYU_ADORER_ABSORPTION,
    EMERALD_TRANSFORMER,
    PERM_FORTUNE,
    PERM_VILLAGER,
    MILICIEN_SUMMONER,
    PERM_SHARPNESS,
    PERM_BLESS

}
