package be.lymaes.race.ability;

public enum AbilityType {

    TASKABLE, CONSUMER, CRAFTER, COMMAND_SENDER, DAMAGER, DEFENDER, KILLER, INTERACT, HELDER, MERCHANT, RAID_WINNER, SNEAKER, TARGETABLE

}
