package be.lymaes.race.ability;

public enum AbilityType {

    TASKABLE, BLOCK_BREAKER, BLOCK_PLACER, CONSUMER, DAMAGER, DEFENDER, FLY, KILLER, INTERACT, ITEM_DROPPING, HELDER, MERCHANT, RAID_WINNER, SNEAKER, TARGETABLE

}
