package be.lymaes.race.ability;

public enum AbilityType {

    TASKABLE, BLOCK_BREAKER, CONSUMER, DAMAGER, DEFENDER, KILLER, INTERACT, ITEM_DROPPING, HELDER, MERCHANT, RAID_WINNER, SNEAKER, TARGETABLE

}
